name: Metrics

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2.3.4

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: solotov-val
          template: classic
          output: './github-metrics.svg'
          config_options: '{"base.header.logo":"https://github.com/solotov-val/solotov-val/blob/main/github-metrics.svg", "base.plugins.lines": true, "base.plugins.languages": true}'

      - name: Commit and push changes
        run: |
          git config --global user.name "solotov-val"
          git config --global user.email "your.email@example.com"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Update metrics"
          git push
