name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Platane/snk@master
        id: snake-svg
        with:
          github_user_name: solotov-val
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14

      - name: Install and use svg2img
        run: |
          npm install -g svg2img
          npx svg2img dist/github-contribution-grid-snake.svg --type gif --output dist/github-contribution-grid-snake.gif

      - run: git status

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
