name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Fetch and merge remote changes
        run: |
          git fetch origin
          git merge origin/main 

      - uses: Platane/snk@master
        id: snake-svg
        with:
          github_user_name: solotov-val
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14

      - name: Install and use svg2img
        run: |
          npm install -g svg2img
          npx svg2img dist/github-contribution-grid-snake.svg --type gif --output dist/github-contribution-grid-snake.gif

      - run: git status

      - name: Commit and push changes
        run: |
          git config --global user.name "solotov-val"
          git config --global user.email "prillerpatrick@gmail.com"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Update snake game"
          git push origin main # Ensure this is the same as your metrics.yml branch
